#!/usr/bin/env node
/**
 * tools/generate-prompts.mjs
 *
 * Читает промпты из packages/ai-kit/prompts/*.md и генерирует
 * apps/workers/ingest/src/prompts.generated.ts — единственный источник правды
 * для inline-строк, которые CF Workers грузит при бандлинге.
 *
 * Запуск:
 *   node tools/generate-prompts.mjs
 *
 * Коммитить generated-файл в репо: VPS деплой не запускает prebuild.
 */

import { readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

function readPrompt(relPath) {
  return readFileSync(resolve(root, relPath), "utf8").trim();
}

const EXTRACT = readPrompt("packages/ai-kit/prompts/intake_extract.md");
const ASSESS  = readPrompt("packages/ai-kit/prompts/intake_assess.md");

const output = `// AUTO-GENERATED by tools/generate-prompts.mjs — DO NOT EDIT MANUALLY.
// Source: packages/ai-kit/prompts/intake_extract.md + intake_assess.md
// Regenerate: node tools/generate-prompts.mjs
// Committed to repo: CF Workers deploy on VPS runs without prebuild step.

export const EXTRACT_SYSTEM = ${JSON.stringify(EXTRACT)};

export const ASSESS_SYSTEM = ${JSON.stringify(ASSESS)};
`;

const outPath = resolve(root, "apps/workers/ingest/src/prompts.generated.ts");
writeFileSync(outPath, output, "utf8");
console.log(`✓ Written: apps/workers/ingest/src/prompts.generated.ts`);
